ALTER TABLE companies
  ADD COLUMN active BOOLEAN NOT NULL DEFAULT 'true';

ALTER TABLE workers
  ADD COLUMN active BOOLEAN NOT NULL DEFAULT 'false';

ALTER TABLE companies
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT current_date;


ALTER TABLE workers
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT current_date;